apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: project
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: FRONTEND_IMAGE
          volumeMounts:
          - name: data-volume
            mountPath: /usr/src/app/data
      volumes:
        - name: data-volume
          emptyDir: {}