apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  namespace: project
  name: frontend-rollout
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  strategy:
    canary:
      steps:
      - setWeight: 50
      - analysis:
          templates:
          - templateName: cpu-usage
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: FRONTEND_IMAGE
          ports:
            - containerPort: 8080
          volumeMounts:
          - name: data-volume
            mountPath: /usr/src/app/data
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 10
            httpGet:
              path: /
              port: 8080
          livenessProbe:
            initialDelaySeconds: 20
            periodSeconds: 10
            httpGet:
              path: /
              port: 8080
          resources:
            requests:
              cpu: "50m"
              memory: "40Mi"
            limits:
              cpu: "125m"
              memory: "50Mi"
      volumes:
        - name: data-volume
          emptyDir: {}