kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dummysite-controller
rules:
  - apiGroups: ['']
    resources: ['pods']
    verbs: ['get', 'list', 'watch', 'create', 'delete']
  - apiGroups: ['']
    resources: ['services']
    verbs: ['create', 'delete']
  - apiGroups: ['networking.k8s.io']
    resources: ['ingresses']
    verbs: ['create', 'delete']
  - apiGroups: ['kekalainen.me']
    resources: ['dummysites']
    verbs: ['get', 'list', 'watch', 'create', 'delete']
