apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: dummysites.kekalainen.me
spec:
  group: kekalainen.me
  names:
    plural: dummysites
    singular: dummysite
    kind: DummySite
    shortNames:
      - ds
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                website_url:
                  type: string
