apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: project
  name: daily-todo-cronjob
spec:
  schedule: "@daily"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: daily-todo
            image: DAILY_TODO_IMAGE
            env:
              - name: BACKEND_URL
                value: http://backend-service:8070
            resources:
              requests:
                cpu: "5m"
                memory: "20Mi"
              limits:
                cpu: "50m"
                memory: "50Mi"
          restartPolicy: OnFailure