apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: main
  name: hashgenerator-persistent-volume-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi