apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nats-servicemonitor
  namespace: prometheus
  labels:
    release: kube-prometheus-stack-1625247232
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: nats
  endpoints:
    - interval: 10s
      path: /metrics
      port: metrics
  namespaceSelector:
    matchNames:
      - nats