apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: postgres-secret
  namespace: project
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgA085SrAJjlW3EaLsaxQijMFVoN+Vioz6oOZK31M7+CmlFZxkxItvRWWkpCZ/+kOk6pIIUZ7XNExJ6MbY8ltq6/5XTBAQloO8h3ssgstUcMvdGC/lfG8SvLSvg80WXTKTMVqfgQY0qkf0sAnoBbpmqnMjRzpOKfPRYnA0hnUeUTDQuZIxNEh6maJmZRXMGmQGe+mZ7qalt1KjeUhwvcjTYmWFA7EV6D7wfixuddTXeC8nEMBSuKf/Vy035Ms6vuX6WlKjtZ1wFiXgWK2DXTmrCIGyTwtnBQ3LmN6u/eWn9D4rmFX1zMOpAwWzCWU9/8aAZePJHIkVrOIsAgd7mpUJCXtY82Y8ViUtxNS1UMn1PDIQohK5p9WdSdyffZQjSKmTmyrc9LfGBFQh8JNKC+Fr6whF+dkFL3yi/BSh30OzUCn7wOa7t3+CmRJJQ01qv14IwmdfI0+HyA1/kG1wsGDoySXu/RzGUiCqaxaa39++AzzHxUT3LiKM7ViECuunLVoS0tVqJfni1f4rhw+AjlKsLRHbz3uMAmrkZ1PU/yyNVheFPyMS9fjCwiK3FAM9YAKf7bhbCvknLNmxWojH4WFtBKVKi2aU53cd7Vre8Avmf6EnWIXFkGRTmRkxN6Qs3YYwLWHMv4QL1IxiAe2wvghfH7c4kQWOIJMExTS6VYxq5cvyqdfUsLXHUAzPGMCw0L+sl9WHwyhBpDZTzRNrU=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: postgres-secret
      namespace: project