apiVersion: v1
kind: Service
metadata:
  namespace: project
  name: backend-service
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - name: http
      protocol: TCP
      port: 8070
      targetPort: 8070