apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- backend/manifests/namespace.yaml
- backend/manifests/analysistemplate.yaml
- backend/manifests/rollout.yaml
- backend/manifests/ingress.yaml
- backend/manifests/postgres-sealedsecret.yaml
- backend/manifests/postgres.yaml
- backend/manifests/service.yaml
- broadcaster/manifests/rollout.yaml
- broadcaster/manifests/broadcaster-sealedsecret.yaml
- broadcaster/manifests/servicemonitor.yaml
- daily-todo/manifests/cronjob.yaml
- frontend/manifests/rollout.yaml
- frontend/manifests/service.yaml

images:
- name: BACKEND_IMAGE
  newName: ghcr.io/kekalainen/uh-dwk-project-backend
  newTag: a5ad7a9620f6ffbc624e9e2d3322e5c62088813f
- name: BROADCASTER_IMAGE
  newName: ghcr.io/kekalainen/uh-dwk-project-broadcaster
  newTag: a5ad7a9620f6ffbc624e9e2d3322e5c62088813f
- name: DAILY_TODO_IMAGE
  newName: ghcr.io/kekalainen/uh-dwk-project-daily-todo
  newTag: a5ad7a9620f6ffbc624e9e2d3322e5c62088813f
- name: FRONTEND_IMAGE
  newName: ghcr.io/kekalainen/uh-dwk-project-frontend
  newTag: a5ad7a9620f6ffbc624e9e2d3322e5c62088813f
