apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secret
  namespace: main
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgCn4ZzxyD8lQ2INTjZ/saZOwjNE0Ezrekm7lCqmphkH67SibsmBD+fNviWJbZto8rxlNW1eEMlkrX4BxPzcKHlaqoo7X/l6Jzfyv9QRy0W7TCfmergza1Ks9u8E+Q2ntklYKy5IERaKfqyNvjQoy7qXGoaMjmF3d+jmpCHA6ObriNMEha3e7UU+dl4tkINzVZ6W76qlaJjZoWEUTwQ+N3sxBFmiT5H7EhXifW26lhKnksTNYPDArsXjUx6BlbmVU0j38w9BreubmdGVNxyPQjxUPL/5imiqu5QO448xna5JT/t6qvWvKD2wIF8jF+MNPJnc5qTVBY9mKwn5tDtRMHCnfQ+Y1QfVHddzUII9/kHEp2HWsax18TJxi8RRy2cnmLAD4gtxzwtGk7zqFI1/d4Dp1lN6KLNDFG9wK1jfdCjo9Z7fHzkJc5FHylNeRVcft1dbbc87my4MQucdGfey9kgzpaszeiJm3fwOKs5oUIVI+UNHI05WXOBAT1pO2hUyOIaSS4yGO59Zl76wwm61y2Sp+L4h4J0dOnf4ZtCS1J5FRdUsutZak1tpGTfpYK4axDGV1rrmwd61X108AAZvO4SAjlUM1fR9OdIcFarHoft1vFgZukwkWkT0dltKw1yghGN5QvIPBAhsDE8s1CLst2Ct5wDjjxQnImtedEyx+/QfiQwAYtTPrmtHNeNKuUHyWh6i9HZ1I7dk
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: postgres-secret
      namespace: main