apiVersion: v1
kind: Service
metadata:
  namespace: main
  name: ping-pong-service
spec:
  type: NodePort
  selector:
    app: ping-pong
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080