apiVersion: v1
kind: Service
metadata:
  name: web-server-service
spec:
  type: ClusterIP
  selector:
    app: web-server
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080