name: Build and update release manifest

on:
  push:
      branches:
        - master
      paths:
        - '.github/workflows/project-gitops.yaml'
        - 'project-app/**'

jobs:
  setup-build-push-commit:
    name: Setup, build, push and commit
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Define image tags
      run: |
        echo "BACKEND_IMAGE_TAG=ghcr.io/${{ github.actor }}/uh-dwk-project-backend:$GITHUB_SHA" >> $GITHUB_ENV
        echo "BROADCASTER_IMAGE_TAG=ghcr.io/${{ github.actor }}/uh-dwk-project-broadcaster:$GITHUB_SHA" >> $GITHUB_ENV
        echo "DAILY_TODO_IMAGE_TAG=ghcr.io/${{ github.actor }}/uh-dwk-project-daily-todo:$GITHUB_SHA" >> $GITHUB_ENV
        echo "FRONTEND_IMAGE_TAG=ghcr.io/${{ github.actor }}/uh-dwk-project-frontend:$GITHUB_SHA" >> $GITHUB_ENV

    - name: Build images
      run: |
        docker build --tag "$BACKEND_IMAGE_TAG" ./backend
        docker build --tag "$BROADCASTER_IMAGE_TAG" ./broadcaster
        docker build --tag "$DAILY_TODO_IMAGE_TAG" ./daily-todo
        docker build --tag "$FRONTEND_IMAGE_TAG" ./frontend
      working-directory: project-app

    - name: Push images
      run: |
        docker push "$BACKEND_IMAGE_TAG"
        docker push "$BROADCASTER_IMAGE_TAG"
        docker push "$DAILY_TODO_IMAGE_TAG"
        docker push "$FRONTEND_IMAGE_TAG"

    - name: Set up Kustomize
      run: |
        curl -sfL https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv4.2.0/kustomize_v4.2.0_linux_amd64.tar.gz | tar xz
        chmod u+x ./kustomize

    - name: Update kustomization manifest images
      run: |
        ../kustomize edit set image BACKEND_IMAGE=$BACKEND_IMAGE_TAG
        ../kustomize edit set image BROADCASTER_IMAGE=$BROADCASTER_IMAGE_TAG
        ../kustomize edit set image DAILY_TODO_IMAGE=$DAILY_TODO_IMAGE_TAG
        ../kustomize edit set image FRONTEND_IMAGE=$FRONTEND_IMAGE_TAG
      working-directory: project-app

    - name: Commit changes to release branch
      uses: EndBug/add-and-commit@v7
      with:
        add: 'project-app/kustomization.yaml'
        branch: release
        pull_strategy: 'NO-PULL'
        push: origin release --force