name: Delete deployment from GKE

on: delete

env:
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-north1-a

jobs:
  setup-teardown:
    name: Setup and tear down
    runs-on: ubuntu-latest
    steps:

    - name: Configure Google Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Update kubeconfig with cluster credentials
      run: gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"

    - name: Teardown
      run: kubectl delete namespace project-${{ github.event.ref }}