name: Build and deploy to GKE

on:
  push:
      paths:
        - "project-app/**"

env:
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-north1-a

jobs:
  setup-build-push-deploy:
    name: Setup, build, push and deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: project-app
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure Google Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Register Docker credential helper
      run: gcloud --quiet auth configure-docker

    - name: Update kubeconfig with cluster credentials
      run: gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"

    - name: Define image tags
      run: |
        echo "BACKEND_IMAGE_TAG=gcr.io/${{ secrets.GCP_PROJECT_ID }}/project-backend:${GITHUB_REF#refs/heads/}-$GITHUB_SHA" >> $GITHUB_ENV
        echo "DAILY_TODO_IMAGE_TAG=gcr.io/${{ secrets.GCP_PROJECT_ID }}/project-daily-todo:${GITHUB_REF#refs/heads/}-$GITHUB_SHA" >> $GITHUB_ENV
        echo "FRONTEND_IMAGE_TAG=gcr.io/${{ secrets.GCP_PROJECT_ID }}/project-frontend:${GITHUB_REF#refs/heads/}-$GITHUB_SHA" >> $GITHUB_ENV

    - name: Build images
      run: |
        docker build --tag "$BACKEND_IMAGE_TAG" ./backend
        docker build --tag "$DAILY_TODO_IMAGE_TAG" ./daily-todo
        docker build --tag "$FRONTEND_IMAGE_TAG" ./frontend

    - name: Push images
      run: |
        docker push "$BACKEND_IMAGE_TAG"
        docker push "$DAILY_TODO_IMAGE_TAG"
        docker push "$FRONTEND_IMAGE_TAG"

    - name: Set up Kustomize
      run: |
        curl -sfL https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv4.2.0/kustomize_v4.2.0_linux_amd64.tar.gz | tar xz
        chmod u+x ./kustomize

    - name: Deploy
      run: |
        kubectl create namespace project-${GITHUB_REF#refs/heads/} || true
        ./kustomize edit set namespace project-${GITHUB_REF#refs/heads/}
        ./kustomize edit set image BACKEND_IMAGE=$BACKEND_IMAGE_TAG
        ./kustomize edit set image DAILY_TODO_IMAGE=$DAILY_TODO_IMAGE_TAG
        ./kustomize edit set image FRONTEND_IMAGE=$FRONTEND_IMAGE_TAG
        kubectl apply -k .